Admin node-sass version from 4.13.1 to 4.14.1
shopware/shopware pull request #1061
Opened 2020-06-22 09:55 UTC by granitibrahimi

Update packages.json due to errors encountered on Ubuntu: "Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsuported Runtime (83)"

Updating the node-sass fixed the issue.

![image](https://user-images.githubusercontent.com/16402164/85272443-77f96980-b47c-11ea-996a-378e301d683a.png)

### 1. Why is this change necessary?

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2020-06-25 06:36 UTC, raknison requested changes
Hi @granitibrahimi,

thank you for your contribution. Please revert the change of `version` in the `package-lock.json` file.

2020-06-25 06:36 UTC, raknison commented on src/Administration/Resources/app/administration/package-lock.json
> +    "version": "6.2.1",
@granitibrahimi Please can you revert this change? - The version should be `1.0.0`

2020-06-25 06:53 UTC, granitibrahimi commented
> Hi @granitibrahimi,
> 
> thank you for your contribution. Please revert the change of `version` in the `package-lock.json` file.

Hi @raknison,

version is reverted to 1.0.0.

2020-06-25 07:02 UTC, raknison commented
> > Hi @granitibrahimi,
> > thank you for your contribution. Please revert the change of `version` in the `package-lock.json` file.
> 
> Hi @raknison,
> 
> version is reverted to 1.0.0.

@granitibrahimi Sorry, please squash your commits.

2020-06-26 08:20 UTC, granitibrahimi commented
> > > Hi @granitibrahimi,
> > > thank you for your contribution. Please revert the change of `version` in the `package-lock.json` file.
> > 
> > 
> > Hi @raknison,
> > version is reverted to 1.0.0.
> 
> @granitibrahimi Sorry, please squash your commits.

@raknison I tried at least lol, but I`m not sure I did it right. Probably I need a hand :(

2020-06-26 08:34 UTC, raknison commented
> > > > Hi @granitibrahimi,
> > > > thank you for your contribution. Please revert the change of `version` in the `package-lock.json` file.
> > > 
> > > 
> > > Hi @raknison,
> > > version is reverted to 1.0.0.
> > 
> > 
> > @granitibrahimi Sorry, please squash your commits.
> 
> @raknison I tried at least lol, but I`m not sure I did it right. Probably I need a hand :(

@granitibrahimi  I try to fix that for you later that day, allright?

2020-06-29 13:18 UTC, granitibrahimi commented
> > > > > Hi @granitibrahimi,
> > > > > thank you for your contribution. Please revert the change of `version` in the `package-lock.json` file.
> > > > 
> > > > 
> > > > Hi @raknison,
> > > > version is reverted to 1.0.0.
> > > 
> > > 
> > > @granitibrahimi Sorry, please squash your commits.
> > 
> > 
> > @raknison I tried at least lol, but I`m not sure I did it right. Probably I need a hand :(
> 
> @granitibrahimi I try to fix that for you later that day, allright?

Hi @raknison 

thank you very much. Would like to get a hint how this is done if that is ok with you!

Thanks

2020-07-07 06:36 UTC, raknison commented
Hi @granitibrahimi 

thank you for your contribution 🎉
Your PR was merged to 6.2

Best regards
Markus

2020-07-07 06:36 UTC, closed without merging