Update address-personal.html.twig
shopware/shopware pull request #1183
Opened 2020-07-24 14:00 UTC by sebastianlenz

BUGFIX for validation errors.

### 1. Why is this change necessary?
Without these changes the "I am" field is not preselected after error on vat id validation error.
 
### 2. What does this change do, exactly?
Fix the error.

### 3. Describe each step to reproduce the issue or behaviour.
Currently i could only reproduce this with our plugin in versions < 1.0.1
https://store.shopware.com/lenz698198643790/umsatzsteuer-ustid-validierung-pro-sw6.html

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2020-07-24 14:32 UTC, mitelg requested changes

2020-07-24 14:32 UTC, mitelg commented on src/Storefront/Resources/views/storefront/component/address/address-personal.html.twig
> +                                <option>test</option>
please remove 😉

2020-07-24 14:42 UTC, sebastianlenz commented on src/Storefront/Resources/views/storefront/component/address/address-personal.html.twig
> +                                <option>test</option>
Done. :)

2020-12-16 09:17 UTC, bneumann97 commented
Hey @sebastianlenz, thanks for your contribution 💙  Could you please add a [changelog](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) file?

2021-01-08 13:27 UTC, J-Rahe commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2021-01-08 13:27 UTC, closed without merging