Sort component overrides on usage instead on insertion
shopware/shopware pull request #1248
Opened 2020-08-14 20:59 UTC by JoshuaBehrens

### 1. Why is this change necessary?
When two plugins override a core component they are fooled into the option to control the override order.

### 2. What does this change do, exactly?
Postpone override sorting to overriden object building to manage the order more reliable.

### 3. Describe each step to reproduce the issue or behaviour.
1. Have a plugin that overrides a core component and adds more twig blocks
2. Have a second plugin that overrides the same core component to change content of the newly added twig blocks
3. To ensure the twig inheritance order add a high index as third parameter to `Shopware.Component.override`
4. Still be first in twig inheritance order as the index is ignored

So we have to `Shopware.Component.override` calls which I alias as `thirdParty` and `me`. `me` wants to extend `thirdParty`. As the order of plugins being injected into the administration and the way the browser loads the injected files is sort-of random the order of these calls is random as well. Lets iterate the possible orders and their outcome.

```js
thirdParty(); // triggers push as no index is given
me(100); // triggers splice as an index is given which is similar to a push
```

This results in `me` being last but not by the fact that `me` passed in an index. Any index > 0 would have the same outcome. So this ok as outcome but not reliable.

```js
me(100); // triggers push as no other overridees are registered
thirdParty(); // triggers push as no index is given
```

This results in `me` being first so `me` can't extend the block that is created by `thirdParty`. Any index `me` passes in won't help `me` when `me` is the first registered overridee. This is not working out and not reliable at all.

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-08-14 22:42 UTC, shyim commented
Please add jest tests

2020-08-19 01:33 UTC, JoshuaBehrens commented
I changed the code and do not store the config and index separately but store the index into the configuration. This way the storage structure is less changed and therefore less tests are in need to be changed and those who tamper with the registry right now don't have to change as well.

I added a test case. Thanks to @leichteckig for the admin test intro

2020-11-23 14:40 UTC, philipgatzka requested changes
Hi @JoshuaBehrens , thank you for this PR :slightly_smiling_face: The test you've added is failing as far as I can tell (I've tested it locally, since the logs have been deleted from github already):
```
● core/factory/component.factory.js › should register two overrides of an existing component in the override registry (with index)

    expect(received).toBe(expected) // Object.is equality

    Expected: "This is the second override."
    Received: "This is the first override."

      195 |             expect(typeof overrideRegistry.get('test-component')[0].methods.testMethod).toBe('function');
      196 |             expect(typeof overrideRegistry.get('test-component')[1].methods.testMethod).toBe('function');
    > 197 |             expect(overrideRegistry.get('test-component')[0].methods.testMethod()).toBe('This is the second override.');
          |                                                                                    ^
      198 |             expect(overrideRegistry.get('test-component')[1].methods.testMethod()).toBe('This is the first override.');
      199 |         }
      200 |     );
```
Also, please add a changelog describing your changes.

2020-11-23 14:53 UTC, JoshuaBehrens commented
That is why I still have this branch checked out locally 😅 thanks for the hint. I'll have a look at it.

2020-12-07 10:27 UTC, J-Rahe commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2020-12-07 10:27 UTC, closed without merging