Mark active navigation
shopware/shopware pull request #1277
Opened 2020-08-26 19:07 UTC by tinect

### 1. Why is this change necessary?
There is no marking of active category in navigation.

### 2. What does this change do, exactly?
Add style to active navigation.
![image](https://user-images.githubusercontent.com/135993/91345762-2bb20900-e7e0-11ea-8a2c-861226142463.png)

### 3. Describe each step to reproduce the issue or behaviour.
Visit navigation, fly out the navigation, see it isn't marked.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-11-06 10:56 UTC, philipgatzka requested changes
Hey @tinect , please add a changelog for this change :slightly_smiling_face:

2020-11-09 07:15 UTC, philipgatzka approved these changes

2020-11-11 09:13 UTC, tinect commented
PR marked as draft. Will catch product paths soon, too.
Memo: `page.product.categoryTree`

2021-01-11 10:19 UTC, closed without merging

2021-01-11 10:20 UTC, philipgatzka commented
Hey @tinect , thank you for your contribution! 🎉