Change displaying not installed plugins
shopware/shopware pull request #1286
Opened 2020-08-27 15:03 UTC by tinect

### 1. Why is this change necessary?
We should display info without any mouseover.
![image](https://user-images.githubusercontent.com/135993/91459669-2e1b6e00-e887-11ea-8c1e-114faf1d3712.png)

### 2. What does this change do, exactly?
Replaced tooltip with a label.
![image](https://user-images.githubusercontent.com/135993/91459413-ea286900-e886-11ea-8a8a-fc97dd14b262.png)

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-08-27 18:21 UTC, mitelg commented on src/Administration/Resources/app/administration/src/module/sw-plugin/snippet/de-DE.json
> +            "tooltipActivationDisabled": "Du kannst nur installierte Plugins aktivieren.",
could we remove this snippet?

2020-08-27 21:08 UTC, tinect commented on src/Administration/Resources/app/administration/src/module/sw-plugin/snippet/de-DE.json
> +            "tooltipActivationDisabled": "Du kannst nur installierte Plugins aktivieren.",
Suuuuuure... yes, we should :-)

2020-11-20 13:49 UTC, philipgatzka requested changes
Hi @tinect , thank you for creating this pull request, great idea! Would you mind changing the version of the status indicator to the same we're already using for the order status? So `sw-label` is fine, but use the `pill` shape with the `neutral` colour setting instead. Besides that, please add a changelog entry for your changes :slightly_smiling_face:

2020-12-08 10:21 UTC, J-Rahe commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2020-12-08 10:21 UTC, closed without merging