add properties to productstream field selection
shopware/shopware pull request #1287
Opened 2020-08-28 08:04 UTC by FalkoHilbert

### 1. Why is this change necessary?
This small change has the effect that the item properties are also available in the Selection field for the configuration of dynamic product groups.
This is particularly useful if the dynamic product groups are based on properties such as e.g. the color or size to be filtered.

### 2. What does this change do, exactly?
removes the product properties from the blacklist

### 3. Describe each step to reproduce the issue or behaviour.
create an dynamic productgroup an choose 'properties'

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-08-28 09:43 UTC, pweyck commented
Please change the destination branch to master. The feature set of the 6.3.1.0 is frozen, the branch is only for testing.

2020-08-31 07:24 UTC, FalkoHilbert commented
> Please change the destination branch to master. The feature set of the 6.3.1.0 is frozen, the branch is only for testing.

@pweyck destination branch is changed to master

2020-10-20 07:18 UTC, FalkoHilbert commented
@pweyck why is my PR not processed?

2020-10-23 15:06 UTC, Guite commented
:+1: for this

2020-11-12 12:10 UTC, philipgatzka requested changes
Hey @FalkoHilbert , thank you for creating this pull request :slightly_smiling_face: Please make sure that the values are translated properly (users should not see any technical values in the administration).

2020-11-12 16:31 UTC, FalkoHilbert commented
@philipgatzka The selection for the properties should now be translated

2020-11-24 13:50 UTC, philipgatzka requested changes
Hi @FalkoHilbert , I quickly checked this out and would like to ask you to add the following:
- Translations for example for `property_group` and `property_group_option` which show up, when selecting Property -> Group
- Testcases verifying this new behaviour works as intended (for example in the form of [Jest tests](https://docs.shopware.com/en/shopware-platform-dev-en/references-internals/testing/jest))
- A changelog describing the changes done here

Please address these and I think we're good to go :slightly_smiling_face:

2020-12-08 10:21 UTC, J-Rahe commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2020-12-08 10:21 UTC, closed without merging

2021-01-31 21:10 UTC, LostKatana commented
@FalkoHilbert What about this issue?

2021-02-15 13:19 UTC, FalkoHilbert commented
i think it would resolved with feature https://issues.shopware.com/issues/NEXT-12108
so i wouldn't reopen this PR