Add twig blocks for contact form on administration & storefront
shopware/shopware pull request #1402
Opened 2020-10-07 12:38 UTC by runelaenen

### 1. Why is this change necessary?
Allow proper customisation by plugins of the content forms.

### 2. What does this change do, exactly?
# Administration
*  Add `sw_cms_el_form_config_content_form_type_options` block around select options of form type.
---
# Storefront
*  Add `element_form_wrapper` block around form type renderers.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-10-08 10:01 UTC, pweyck requested changes

2020-10-08 10:01 UTC, pweyck commented on changelog/_unreleased/2020-10-05-form-element-config-type-options.md
> +*  Add `sw_cms_el_form_config_content_form_type_options` block around select options of form type.
https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md
```suggestion
*  Added `sw_cms_el_form_config_content_form_type_options` block around select options of form type.
```

2020-10-08 10:01 UTC, pweyck commented on changelog/_unreleased/2020-10-05-form-element-config-type-options.md
> +*  Add `element_form_wrapper` block around form type renderers.
```suggestion
*  Added `element_form_wrapper` block around form type renderers.
```

2020-10-08 10:01 UTC, pweyck commented on changelog/_unreleased/2020-10-05-form-element-config-type-options.md
> +---
```suggestion
___
```

2020-10-08 10:06 UTC, runelaenen commented
@pweyck I applied the suggestions to the changelog file. Keep in mind that things like the line (---) that you changed to (___) was actually generated by the console command.

2020-10-12 09:33 UTC, closed without merging

2020-10-12 09:43 UTC, bneumann97 commented
Hey @runelaenen, thanks for your contribution 💙