Fix #1412 Multiple option values
shopware/shopware pull request #1413
Opened 2020-10-13 14:09 UTC by runelaenen

### 1. Why is this change necessary?
The $sorted[x] keeps getting overwritten by the latests option it tries to assign. This made only 1 option visible in the frontend.

### 2. What does this change do, exactly?
Stop overriding the variable.

### 3. Describe each step to reproduce the issue or behaviour.
Choose multiple option values, check out the PDP.

### 4. Please link to the relevant issues (if any).
#1412 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-10-15 09:45 UTC, PaddyS commented
Please add a changelog :-)

2020-10-15 09:58 UTC, runelaenen commented
> Please add a changelog :-)

I've added a changelog entry.

2020-10-20 10:22 UTC, akucharczyk approved these changes

2020-11-03 10:36 UTC, jleifeld commented on changelog/_unreleased/2020-10-15-bugfix-multiple-option-values.md
> +*  Fixed the calculation of sortedProperties in `Shopware\Core\Content\Product\Subscriber\ProductSubscriber`
Fixed is not a keyword

2020-11-05 08:37 UTC, philipgatzka requested changes
Hi @runelaenen , thank you for this PR :slightly_smiling_face: Please have a look at the review comments and also add tests for your change.

2020-11-05 08:37 UTC, philipgatzka commented on src/Core/Content/Product/Subscriber/ProductSubscriber.php
> +            $group = $sorted[$origin->getId()] ?? $sorted[$origin->getId()] = clone $origin;
Please do not use the shorthand form here since it doesn't improve readability in this case.

2020-11-20 10:29 UTC, philipgatzka commented
Hey @runelaenen , we're closing this pull request due to inactivity. If this change is still important to you, feel free to create a new pull request.

For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline.

2020-11-20 10:29 UTC, closed without merging

2020-11-20 11:16 UTC, runelaenen commented
Seems like the issues was already fixed: NEXT-11258