NEXT-11540 - Added quantity-selection
shopware/shopware pull request #1439
Opened 2020-10-21 13:23 UTC by tinect

### 1. Why is this change necessary?
We should switch to an input-field when quantity-selection would have too many options.

### 2. What does this change do, exactly?
#### Storefront
* Added new utility template `storefront/utilities/quantity-selection.html.twig` to take care of input or select output
* Changed block `component_offcanvas_product_buy_quantity` in `component/checkout/offcanvas-item.html.twig` to use new utility
* Changed block `page_product_detail_buy_quantity` in `page/checkout/checkout-item.html.twig` to use new utility
* Changed block `page_product_detail_buy_quantity` in `page/product-detail/buy-widget-form.html.twig` to use new utility
* TODO: Add migration
#### Administration
* Added config `cart.maxSelectFieldOptions` in cart settings to specifiy when input field should be displayed instead of the select field

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-11540

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-10-21 13:56 UTC, mitelg commented
did you check if there is some validation on backend site? like if I want to order a quantity of "beer" products?

2020-10-21 14:22 UTC, tinect commented
> did you check if there is some validation on backend site? like if I want to order a quantity of "beer" products?

@mitelg Please give me a hint, what you mean :-) Yes, there are some validations, like steps, maxPurchase in Core 🤔

2020-10-21 14:25 UTC, mitelg commented
if the selection switches to an input field, is the actual input given by the customer validated by the core? no, I don't mean HTML5 validation.

so it is possible to put "beer" products in the cart? or does Shopware says: sorry but this is not a valid quantity

2020-10-21 14:42 UTC, tinect commented
Will check it ;-)

2020-11-02 10:17 UTC, philipgatzka requested changes
Hey @tinect , thank you for submitting this pull request!

This is a great idea, there are some things we need to check though before a change like this can be integrated:

- The configuration does not need to be dependent on the amount of options shown. Please change it to a general option which toggles between a select and an input field. This option should be set to show the select field (current behaviour) by default and configurable per sales-channel.
- Please change the error message in the offcanvas cart (the one that is shown when users submit a wrong value like text instead of numbers) to a more specific one
- Also, please make sure that this works on mobile devices, ideally with different browsers
- Finally, the input should behave correctly with the clearance sale. Please ensure this is the case (this could be done with automated tests)

I'll also forward this to our design team, so they can have a look at this change too.

2020-11-19 12:16 UTC, philipgatzka commented
Just FYI - design-wise this is fine, since default browser components are used in the storefront. Are you still on this @tinect ?

2020-11-19 19:47 UTC, tinect commented
Hey @philipgatzka,
Thanks for the information :-) So I can check when I get some free time to make this ready.

2020-11-20 05:19 UTC, philipgatzka commented
Alright :+1: I'll leave this open for now then.

2020-12-04 10:26 UTC, bneumann97 commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2020-12-04 10:26 UTC, closed without merging