NEXT-8058: Added config to make phone number input optional for conta…
shopware/shopware pull request #1456
Opened 2020-10-26 18:19 UTC by claudiobianco

…ct form

### 1. Why is this change necessary?
The phone number input should be optional in the contact form.

### 2. What does this change do, exactly?
- Adds a configuration to basicInformation.xml to make phone number input optional in contact form
- Adds `BuildValidationEvent` in `ContactFormRoute`
- Adds check in storefront if phone input should be marked as required 
- Leaves the default to required to not change the default behaviour

### 3. Describe each step to reproduce the issue or behaviour.
- Submit contact form without phone number
- Enable optional phone number input
- Submit contact form without phone number

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-8058

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-10-26 18:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=1456) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=1456) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=1456) it.</sub>

2020-10-30 13:16 UTC, philipgatzka requested changes
Hey @claudiobianco , thank you for creating this PR!
Please have a look at the suggestions :slightly_smiling_face:

2020-10-30 13:16 UTC, philipgatzka commented on src/Core/Content/ContactForm/SalesChannel/ContactFormRoute.php
> +        }
Hi @claudiobianco , would you mind solving this inside the `\Shopware\Core\Content\ContactForm\Validation\ContactFormValidationFactory`?

2020-10-30 13:16 UTC, philipgatzka commented on src/Core/Content/ContactForm/SalesChannel/ContactFormRoute.php
> +        $this->dispatchValidationEvent($definition, $context->getContext());
:+1: for adding an event. I think extracting the dispatcher call into a method is not necessary here though.

2020-11-03 08:21 UTC, philipgatzka approved these changes
Looks good, thanks :slightly_smiling_face:

2020-11-04 07:16 UTC, philipgatzka requested changes
Hey @claudiobianco , I had another look at this together with a colleague from QA. Unfortunately I only now discovered, that this change does only partially solve the linked issue [NEXT-8085](https://issues.shopware.com/issues/NEXT-8058). Would you mind adding the other two options as well? Apart from that we already have similar switches in the administration, the labelling/behaviour is a bit different there though:

| switch position | result |
|---|---|
| `off` | form input is not required |
| `on` | form input is required |

We'd be glad if you could use the same behaviour for any new switches (toggling `required` behaviour) added here :slightly_smiling_face:

2020-11-05 08:06 UTC, philipgatzka approved these changes
Looks good to me :rocket:

2020-11-12 16:17 UTC, claudiobianco commented
Rebased current master to have successful checks ;)

2020-11-20 12:41 UTC, closed without merging

2020-11-20 12:44 UTC, philipgatzka commented
Hey @claudiobianco , thank you very much for your contribution! :tada: