NEXT-12049 Add cache for different json responses
shopware/shopware pull request #1496
Opened 2020-11-10 19:40 UTC by tinect

### 1. Why is this change necessary?
Different Json responses don't use the HttpCache proper as it's defined in the annotation. The header `AbstractSessionListener::NO_AUTO_CACHE_CONTROL_HEADER` is missing. It's just set when using renderStorefront.

### 2. What does this change do, exactly?
Add the header before sending result.

### 3. Describe each step to reproduce the issue or behaviour.
- Activate HttpCache
- Add `time()` to JsonResponse of route `fronted.detail.switch`
- Call a switch-url
- Notice the timestamp
- Refresh the switch-url
- See new timestamp
- Booooom, http-cache not correct used

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-12049

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-11-24 13:26 UTC, philipgatzka requested changes
Thank you for creating this pull request @tinect ! Please complete our contribution guidelines, by adding simple testcases which assert that the desired Header gets sent.

2020-11-24 19:22 UTC, tinect commented
> Thank you for creating this pull request @tinect ! Please complete our contribution guidelines, by adding simple testcases which assert that the desired Header gets sent.

Hey @philipgatzka 

I'm not familiar with tests that much :-( You call it `simple`, I call it `¯\_(ツ)_/¯`
Any help would be great, cause this header is removed before response 🤔 I don't know how to get into it.

2020-11-25 07:38 UTC, philipgatzka commented
No worries, and sorry if that sounded like I wanted to trivialise writing tests - it's not always easy of course, I meant that more in regard to the needed assertions. You could go with a test like this in the existing `SearchControllerTest` class for example:

```php
public function testFilterResponseContainsCorrectCacheHeader(): void
{
    $controller = $this->getContainer()->get(SearchController::class);
    $salesChannelContextFactory = $this->getContainer()->get(SalesChannelContextFactory::class);

    $request = new Request();
    $request->request->set('search', true);
    $salesChannelContext = $salesChannelContextFactory->create(Uuid::randomHex(), Defaults::SALES_CHANNEL);

    $response = $controller->filter($request, $salesChannelContext);

    static::assertSame($response->headers->get(AbstractSessionListener::NO_AUTO_CACHE_CONTROL_HEADER), '1');
}
```
You could use an almost identical test for the other controllers I think :slightly_smiling_face:

2020-12-15 10:22 UTC, J-Rahe commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2020-12-15 10:22 UTC, closed without merging