Bugfix/next 10262
shopware/shopware pull request #1508
Opened 2020-11-16 10:15 UTC by JoshuaBehrens

### 1. Why is this change necessary?
There are lots of occassions where a complete list of objects is required but not requested properly. Most of these places are visible when you see a criteria limit of 100 or 500. These are tries to load all the data but this is not all the data. This might be the case because although it is tried to have php and admin-js behave identically regarding DAL operations it is not as the criteria in admin-js works with limited pages that have a preset of 1, 25 and the php criteria works with limit offset and has a preset of null, null. Those who work with the admin-js criteria and are familiar with it from php get fooled.

### 2. What does this change do, exactly?
Add the php-known RepositoryIterator and some constants from the criteria. Use the repository iterator at a lot of places that behave better now.

### 3. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-10262
https://issues.shopware.com/issues/NEXT-10349
And probably some more

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-11-16 10:16 UTC, JoshuaBehrens commented
Sorry for the re-open of https://github.com/shopware/platform/pull/1310. I butter-fingered the delete external button :/

2020-11-24 15:15 UTC, philipgatzka requested changes
No worries :slightly_smiling_face: This is a great improvement I think, just the usual nitpicks :wink: Please write a changelog and have a look at my other comment.

2020-11-24 15:15 UTC, philipgatzka commented on src/Administration/Resources/app/administration/src/core/data-new/repository-iterator.data.js
> +    }
Please test the methods in this class.

2020-11-24 15:47 UTC, JoshuaBehrens commented
Being nitpicky is not bad :D I'll have a look at it

2020-12-08 10:23 UTC, J-Rahe commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2020-12-08 10:23 UTC, closed without merging

2021-03-03 15:26 UTC, JoshuaBehrens commented
That moment when you thought you've already fixed it and find the PR declined :< yikes

2021-08-31 19:41 UTC, mitelg commented
reopen it already! 😃

2021-08-31 20:01 UTC, JoshuaBehrens commented
@mitelg :O just reopen? All the rebases I have to do :(

2021-08-31 20:33 UTC, mitelg commented
I guess a new branch/PR and cherry pick would be the better solution 🙂

2021-09-06 14:09 UTC, htkassner commented
We will have a look at it again and I will come back to it @JoshuaBehrens. We think this is useful but have to check some possible side effects

2021-09-06 14:36 UTC, JoshuaBehrens commented
@htkassner I am here :) ready for your side-effects-check

2021-09-14 10:05 UTC, renegr-moonshiner commented
@htkassner hej, since the pullrequest #2049 has been declined, and this has been declined as well, what is your proposed solution and for which releases will it be scheduled? Thanks for a concise answer on that issue (NEXT-14201)

2021-09-14 10:13 UTC, JoshuaBehrens commented
@renegr-moonshiner this is just an out-of-time decline. Not content related.

Still keen to know about the schedule though 🧐

2021-09-14 10:15 UTC, htkassner commented
First thin we will contribute is the solution for the sales channels which has highest prio. This is in the final stages

2021-09-14 16:35 UTC, renegr-moonshiner commented
@htkassner good to hear, that's in the final stages. Which version will receive this bugfix?

2021-09-15 06:28 UTC, htkassner commented
When its working out like we want this should be in the next release in october. Right now I could not say why this wouldn´t work. So let´s c. @renegr-moonshiner

2021-09-20 03:04 UTC, JoshuaBehrens commented
@htkassner @renegr-moonshiner @jochenmanz @mitelg @J-Rahe just a shout-out for those who are already part of this pull request. This got a sequel pull request. Updated and rebased!