Fix deleting indices which are currently exported
shopware/shopware pull request #1529
Opened 2020-11-23 09:08 UTC by henrikvolmer

### 1. Why is this change necessary?
If the indices for with `bin/console dal:refresh:index --use-queue` are exported, then with `bin/console es:index:cleanup -f` also indices are deleted which are currently exported. This behavior is not very useful if the cleanup is done in a cronjob (a constant manual cleanup is not practical here).

### 2. What does this change do, exactly?
Checks if the indices to be deleted are currently exported. If so, it does not delete them.

### 3. Describe each step to reproduce the issue or behaviour.
- start the command `bin/console dal:refresh:index --use-queue`
- start the command `bin/console es:index:cleanup -f`

The new indices which are currently exported will be deleted

### 4. Please link to the relevant issues (if any).
#1528 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-11-23 10:31 UTC, henrikvolmer commented
Currently the pipeline of JS and PHP failed unfortunately. But this seems to be not related to my changes. Can you check this @Shopware

2020-11-27 14:55 UTC, philipgatzka requested changes
Hi @henrikvolmer , thank you for creating this pull request :slightly_smiling_face: Please add a changelog for your changes, as well as a testcase. Apart from this I've only got one minor nitpick :wink:

2020-11-27 14:55 UTC, philipgatzka commented on src/Elasticsearch/Framework/ElasticsearchOutdatedIndexDetector.php
> +            static function (array $col) {
Would you mind using `array_column` here instead? I think that would be a bit more readable.

2020-12-11 10:33 UTC, bneumann97 commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2020-12-11 10:33 UTC, closed without merging