Fix unavailable block type
shopware/shopware pull request #1532
Opened 2020-11-24 14:15 UTC by schuering

### 1. Why is this change necessary?
If a block (based on a block type added by a plugin) is created and the plugin will be deactivated the administration throws the following TypeError: Cannot read property 'removable' of undefined

### 2. What does this change do, exactly?
This change filters blocks by available block types.

### 3. Describe each step to reproduce the issue or behaviour.
- Install a plugin which provides any new block type
- Add a shopping experience which at least one block based on the block type provided by the plugin
- Deactivate the plugin
- Try to edit the shopping experience (and see whats happening in the console)

### 4. Please link to the relevant issues (if any).
#1178 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-11-24 14:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=1532) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=1532) before we can accept your contribution.<br/><hr/>**Jan Schüring** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=1532) it.</sub>

2020-11-27 15:14 UTC, philipgatzka requested changes
Hi @schuering , thank you for creating this pull request! :+1: There's a failing test which seems to be related to the changes done here:

```
● module/sw-cms/component/sw-cms-section › the disable all sub components
	
	    TypeError: Cannot read property 'getCmsBlockRegistry' of undefined
	
	      122 | 
	      123 |         blockTypes() {
	    > 124 |             return Object.keys(this.cmsService.getCmsBlockRegistry())
	          |                                                ^
	      125 |         }
	      126 |     },
	      127 | 
```
Please check this and also implement a regression test covering your changes :slightly_smiling_face:

2020-12-08 07:35 UTC, schuering commented
@philipgatzka Most of the tests have now been passed successfully. Could you check that again, please?

2020-12-14 09:06 UTC, schuering reviewed
Tests have been added, please recheck

2021-01-07 11:02 UTC, philipgatzka approved these changes
Looks fine to me 👍🏼

2021-01-07 12:28 UTC, schuering commented
> Looks fine to me 👍🏼

I'm glad about that. :)

2021-01-08 09:31 UTC, closed without merging

2021-01-08 09:32 UTC, philipgatzka commented
Thank you for contributing @schuering ! 🥳