Initialize custom fields on categories
shopware/shopware pull request #1566
Opened 2020-12-18 15:18 UTC by runelaenen

### 1. Why is this change necessary?
Fixes the issue of https://issues.shopware.com/issues/NEXT-11125

### 2. What does this change do, exactly?
Initialize the custom fields if they are not present in the entity.

### 3. Describe each step to reproduce the issue or behaviour.
Create a new CustomField set
Assign this set to category
Create a new CustomField in this set
Go to categories and switch from one category to another

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-11125

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
-  x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-12-28 10:36 UTC, philipgatzka requested changes
Hi @runelaenen , thank you for taking the time to create this pull request :slightly_smiling_face: Please add a regression test for your change so we can be sure this issue is fixed and doesn't come up again.

2021-01-06 14:53 UTC, runelaenen commented
> Hi @runelaenen , thank you for taking the time to create this pull request 🙂 Please add a regression test for your change so we can be sure this issue is fixed and doesn't come up again.

Is there someone who can push me in the right direction? I'm trying to write a test but it's my first time so I'm not sure I'm doing it correctly.

1. Is there documentation available?
2. What exactly should I test? It's a very small change that (I think) is difficult to write a test for.

2021-01-06 15:07 UTC, philipgatzka commented
Hi there! Yes, there's documentation available for that: https://docs.shopware.com/en/shopware-platform-dev-en/references-internals/testing/jest
I'd say it should suffice to call `onChangeCustomFieldSetSelectionActive` and check, whether `initializeCustomFields` is called, in case `this.entity.customFieldSets` is empty. One can do this for example via the jest.spyOn method: https://jestjs.io/docs/en/jest-object#jestspyonobject-methodname

2021-01-13 10:00 UTC, philipgatzka approved these changes

2021-01-14 07:20 UTC, closed without merging

2021-01-14 14:13 UTC, mitelg commented
thanks for your contribution @runelaenen   👍🎉💙

2021-01-25 16:37 UTC, vogelor commented
after adding this fix to my Shopware i run into the next issue.
The custom fields where saved. But from time to time the category-index was re-indexed. and then the custom fields where overridden with "{}" - means the custom fields are deleted.
and the next problem: "{}" is NOT a serialised JSON string. this means it is not possible to change the custom fields anymore. only the "direct-SQL"  
"update category_translation set suctom-fields = null where custom_fields = '{}'" and then clearing the cache works.
But - once again - only until the categories are reindexed.

2021-01-25 19:19 UTC, mitelg commented
hey @vogelor 
please create an own issue for that https://issues.shopware.com/

2021-02-08 15:47 UTC, vogelor commented
> hey @vogelor
> please create an own issue for that https://issues.shopware.com/

Not necessary. The actual Version 6.3.5.1 fixed my issue ;-)