NEXT-11733 - Allow to fetch customer that is registered as guest
shopware/shopware pull request #1578
Opened 2021-01-04 16:33 UTC by nlx-sascha

When using the guest parameter for the register api call, it is not possible to fetch the customer again.

### 1. Why is this change necessary?
Fetching the account as guest user

### 2. What does this change do, exactly?
Expose the api also for guest accounts

### 3. Describe each step to reproduce the issue or behaviour.
Create a new account `/store-api/v3/account/login` with guest parameter
Try to fetch account with the new token is not allowed 

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-11733

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ x ] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ x ] I have read the contribution requirements and fulfil them.

2021-01-04 16:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=1578) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=1578) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=1578) it.</sub>

2021-01-05 10:33 UTC, philipgatzka requested changes
Hi @nlx-sascha ,

thank you for creating this pull request! Please add a test, as well as a changelog entry for your change 🙂

2021-01-05 13:09 UTC, nlx-sascha commented
Hey @philipgatzka,

tests and documentation are written, but unit tests are still failing.

2021-01-12 15:04 UTC, philipgatzka commented
Hi Sascha, thanks for the update 🙂 Those test failures are a bit odd but the cases seem unrelated.

2021-01-12 15:04 UTC, philipgatzka approved these changes

2021-01-13 07:40 UTC, closed without merging

2021-01-13 07:42 UTC, philipgatzka commented
Thank you for your contribution @nlx-sascha 🥳