Allow guest account to change address after registration
shopware/shopware pull request #1581
Opened 2021-01-04 18:59 UTC by nlx-sascha

### 1. Why is this change necessary?
When an account is created with guest parameter it is not possible to change the shipping address afterwards

### 2. What does this change do, exactly?
Adding the allowGuest parameter to the annotation

### 3. Describe each step to reproduce the issue or behaviour.
* Create an account with the Store Api
* Try to update the activeShippingAddress with the "update an existing address" api
* Get 403 as response

### 4. Please link to the relevant issues (if any).
Didn't find one

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ x ] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ x ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ x ] I have read the contribution requirements and fulfil them.

2021-01-05 10:32 UTC, philipgatzka requested changes
Hi @nlx-sascha ,

thank you for creating this pull request! Please add a test, as well as a changelog entry for your change 🙂

2021-01-05 13:48 UTC, nlx-sascha commented
Hey @philipgatzka,

tests and documentation are written.

2021-01-13 08:21 UTC, philipgatzka approved these changes

2021-03-08 09:21 UTC, bneumann97 commented
Hey @nlx-sascha, thanks for your contribution 💙  It should not be possible for a guest to be able to change his address <ins>after</ins> the order is completed. The guest currently has the possibility to change his address <ins>before</ins> the order is completed in the storefront. With your change, it is possible to change the address even after the order is completed. We do not want this behavior to be changed 🙂

2021-03-08 09:21 UTC, closed without merging

2021-03-08 09:26 UTC, nlx-sascha commented
@bneumann97 thanks for your feedback, but on my test in Jan it wasn't even possible to change the Address after you created a guest account and bevor creating the order. I'm not sure if this is possible with the current trunk, but I think it should.

2021-03-08 09:29 UTC, bneumann97 commented
In the storefront it is possible. With your change it would be possible to change the address after an order is created. This could lead to serious problems. If your problem still persists and you have a better solution feel free to open a new PR 🙂

2021-04-05 11:03 UTC, nlx-sascha commented
Hey @bneumann97,

today I did another test with the current 6.4 RC1 as there are some major changes to the API.
I give it another try and I'm sorry to say but it did not work as you mentioned or maybe I did something wrong.

So here is what I did and give that I already have an item in the basket
```
# Add country id to the context
PATCH /store-api/context
{"countryId":"463d171d921041e281e7c4003005dcbc"}

# Create a guest account for the user
POST /store-api/v3/account/register
{
  "guest": true,
  "salutationId": "2465774732b9488885c7336a0554a248",
  "firstName": "Sascha",
  "lastName": "Nowak",
  "email": "test@example.com",
  "shippingAddress": {
    "salutationId": "2465774732b9488885c7336a0554a248",
    "salutation": null,
    "firstName": "Sascha",
    "lastName": "Nowak",
    "company": "",
    "street": "....",
    "zipcode": "90411",
    "city": "NGB",
    "countryId": "463d171d921041e281e7c4003005dcbc"
  },
  "billingAddress": {
    "salutationId": "2465774732b9488885c7336a0554a248",
    "salutation": null,
    "firstName": "Sascha",
    "lastName": "Nowak",
    "company": "",
    "street": "....",
    "zipcode": "90411",
    "city": "NGB",
    "countryId": "463d171d921041e281e7c4003005dcbc"
  },
  "storefrontUrl": "https://....localhost",
  "includes": {
    "customer": [
      "firstName",
      "lastName",
      "email",
      "shippingAddress",
      "billingAddress,",
      "activeShippingAddress",
      "defaultShippingAddress",
      "addresses"
    ]
  }
}

# Now the user recognise that he had a typo in his address and change it. In this Example I change the city from NGB => Nürnberg
PATCH /store-api/account/address/d9a047c89a014171ad31e5ea58148077
{
  "salutationId": "2465774732b9488885c7336a0554a248",
  "salutation": null,
  "firstName": "Sascha",
  "lastName": "Nowak",
  "company": "",
  "street": "....",
  "zipcode": "90411",
  "city": "Nürnberg",
  "countryId": "463d171d921041e281e7c4003005dcbc"
}

Looking into the `\Shopware\Storefront\Controller\AddressController` there is a really special handling for address in the method `addressBook`. By reading the code im not exactly sure what the method `handleChangeableAddresses` did and there are no tests für the whole `addressBook`, so it is even more complex to understand this code without further debugging. But it seems possible to create new addresses and change default shipping and billing address. How the address change is done in the storefront 

You wrote `With your change it would be possible to change the address after an order is created. This could lead to serious problems.`, but what I didn't understand is, why is it allow to change the address as registered user, isn't it the same there? As I understand the order creation process the addresses of the customer are copied from to an OrderAddressEntity and therefor the address change should not lead to any problem with the order.

I would appreciate to get this kind of feature in next 6.4 release as it is a real use case for headless shop.
If you have further question you can also ping me in the Shopware slack.

Thanks for your time.
Sascha

2021-04-05 18:46 UTC, nlx-sascha commented
Hey @bneumann97,

I did a manuell test and change the shipping address after creating the order with the patch request of the prev comment.
I can confirm that only the shipping address of the customer was changed and not to shipping address of the created order!
Thats what I have expected. What did you do to manipulate the the shipping address of the order or was it only a guess?