Correct bundle administration javascript paths
shopware/shopware pull request #1607
Opened 2021-01-18 15:12 UTC by niklasbuechner

### 1. Why is this change necessary?
The Shopware administration is unable to load a bundle's resources (CSS & JS) if the bundle's name contains `bundle`. This pr adjusts the path determination logic so that these resources can be loaded.

When installing a bundle's (e.g. `MyBundle`) assets, the asset installer copies all public files into a `public/bundles/` directory. It does, however, remove `bundle` from the directory name so that all files are copied to `public/bundles/my` (https://github.com/shopware/platform/blob/master/src/Core/Framework/Plugin/Util/AssetService.php#L79-L84). The administration does not alter the url when trying to load the resources (https://github.com/shopware/platform/blob/master/src/Core/Framework/Api/Controller/InfoController.php#L221-L233). As a result the administration is unable to load these files.

### 2. What does this change do, exactly?
This change adapts the path used to load bundle javascript files.

### 3. Describe each step to reproduce the issue or behaviour.
1. Create a bundle which ends with `bundle`.
2. Add an administration javascript or css resource to the bundle.
3. Install the bundle and reload the administration.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change

**The current infrastructure does not really facilitate a test of this changed functionality. Can you point me in the right direction of how I could test this?**

- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-01-18 15:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=1607) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=1607) before we can accept your contribution.<br/><hr/>**Niklas Buechner** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=1607) it.</sub>

2021-01-18 15:57 UTC, mitelg commented
@JoshuaBehrens didn't you do this in past PR, too? :thinking:

2021-01-18 16:12 UTC, JoshuaBehrens commented
Indeed. I had a PR called something like do bundle:dump like symfony does

2021-01-18 16:13 UTC, JoshuaBehrens commented
It is basically 1000 PRs old :D https://github.com/shopware/platform/pull/650

2021-01-20 07:26 UTC, philipgatzka commented
Hey @niklasbuechner , thank you for investing the time 🙂 Regarding testing - I presume you mean testing this end-to-end is not feasible? I think it should suffice to mock the `filesystem` and make sure that the `deleteDir`/`copy` methods are called with the correct `$targetPath` when providing a bundle name containing "bundle" to the `copyAssetsFromBundle` method. Please correct me if I missed something here, I have not looked into this behaviour very deeply as of now.

2021-01-20 09:19 UTC, JoshuaBehrens commented
No disappointment guys @fixpunkt @niklasbuechner . We should merge our changes as we are both not covering everything so far. It'll just be a win-win for all of us :)

2021-01-29 05:30 UTC, philipgatzka commented
Do you need any further information regarding testing this @niklasbuechner ? As discussed via Slack, my previous comment does not apply here, since I checked the wrong file.

2021-02-04 13:47 UTC, niklasbuechner commented
@philipgatzka I have added a test for this code.

2021-02-08 14:56 UTC, niklasbuechner commented
I just updated this pr fix the tests. The tests do need the `mikey179/vfsstream` package which I have added to the development template since the platform's development dependencies are not installed for the unit tests.

As a result, this pr now depends on the pr in the https://github.com/shopware/development repository: https://github.com/shopware/development/pull/145

2021-02-10 12:33 UTC, philipgatzka requested changes

2021-02-10 12:33 UTC, philipgatzka commented on src/Core/Framework/Test/Api/Controller/InfoControllerTest.php
> +        );
Hi, great idea to abstract away the filesystem 👍🏼 We already have a library doing that in the core though, namely Flysystem. This also offers a fast in-memory adapter for usage in tests. We'd rather not include a new dependency for this, so please consider one of these alternatives:

1. See my suggestion below (quickly thrown together, so better don't take it verbatim 😅) and use the `Local` adapter with a real but temporary file even though it is not as performant asa virtual filesystem
2. Improve the testability of the `InfoController`, for example by replacing the two native `file_exists` calls with Flysystem calls. Then the flysystem adapter could be swapped with the in-memory one [already available](https://github.com/shopware/development/blob/master/composer.json#L52) in the core dependencies for testing

```suggestion
        $rootPath = implode(DIRECTORY_SEPARATOR, [
            sys_get_temp_dir(),
            Uuid::randomHex()
        ]);
        $filePath = 'Resources/public/administration/js/some-functionality-bundle.js';

        $filesystem = new Filesystem(new Local($rootPath));
        $filesystem->write($filePath, '// File contents');

        static::assertTrue($filesystem->has($filePath));

        $kernelMock
            ->expects(static::exactly(1))
            ->method('getBundles')
            ->willReturn([new BundleFixture('SomeFunctionalityBundle', $rootPath)]);

        $config = json_decode($infoController->config()->getContent(), true);
        static::assertArrayHasKey('SomeFunctionalityBundle', $config['bundles']);

        $jsFilePath = explode('?', $config['bundles']['SomeFunctionalityBundle']['js'][0])[0];
        static::assertEquals(
            'bundles/somefunctionality/administration/js/some-functionality-bundle.js',
            $jsFilePath
        );

        $filesystem->getAdapter()->deleteDir('/');

        static::assertFalse($filesystem->has($filePath));
```

2021-02-11 13:30 UTC, niklasbuechner commented
@philipgatzka I have found a solution to implement the test without an extra bundle and without having to clean up temporary folders.

2021-02-12 13:50 UTC, philipgatzka approved these changes
That's a lot simpler 😁

2021-02-16 12:17 UTC, closed without merging

2021-02-16 12:18 UTC, J-Rahe commented
Hey @niklasbuechner thanks for the PR : )