Show 404 page on not found categories
shopware/shopware pull request #308
Opened 2019-11-25 16:08 UTC by hlohaus

### 1. Why is this change necessary?

To show correct error page instead a redirect to home.

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-11-28 09:44 UTC, pantrtxp commented
Hi @hlohaus,

I've checked out your branch and do not get to a 404 page in production mode if I open a Category which does not exist

can you please check this behavior or explain how I can reproduce your workflow?

Sunny regads
Pantrtxp

2019-11-28 10:25 UTC, hlohaus commented
Try open /navigation/09ec6e37ee754b74abcdc95601baffff

2019-12-04 12:47 UTC, pantrtxp commented
Sadly, I can not confirm this behavior. 
If i check out your branch, set it up in production mode, and go to /navigation/someFakeUUID i'll get an `Category "88bae2d5fde54278a8211da8c9c27f2d" not found` exception in `platform/src/Core/Content/Category/Service/NavigationLoader.php`

2020-02-13 06:26 UTC, pantrtxp commented
Hi @hlohaus 

Sorry about the delay.
If you rebase your branch, I'll look into this again.

Sunny regards
Pantrtxp

2020-02-18 12:28 UTC, pantrtxp commented
@hlohaus we have some failing phpunit tests
`StorefrontRoutingTest::testForwardFromAddPromotionToApiFails` and 
`ProductExportControllerTest::testInvalidData`

could you please take a look?

2020-02-27 09:41 UTC, pantrtxp commented
Hi @hlohaus 

```
Failed asserting that 412 is identical to 404.
 /app/platform/src/Storefront/Test/Controller/StorefrontRoutingTest.php:47
```

This Test is stell failing
Can you look this up please?

2020-02-27 10:04 UTC, hlohaus commented
Yes, thats right. InvalidRouteScopeException has 412 as status code

2020-03-02 09:46 UTC, pantrtxp requested changes

2020-03-02 09:46 UTC, pantrtxp commented on src/Storefront/Test/Framework/Controller/ProductExportControllerTest.php
> +        static::assertEquals(404, $client->getResponse()->getStatusCode());
Please us the constant here as well

2020-03-05 13:30 UTC, pantrtxp commented
Thank you for your contribution @hlohaus

2020-03-05 17:53 UTC, closed without merging