Add twig block to body class
shopware/shopware pull request #366
Opened 2019-12-11 21:16 UTC by stefanpoensgen

### 1. Why is this change necessary?
Currently there is no easy way to extend classes in body tag like in sw5

### 2. What does this change do, exactly?
Add twig block to body class

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2019-12-12 07:10 UTC, keulinho requested changes
Thanks @stefanpoensgen for your contribution,

could you please use more specific block names for the cms and error pages? 
So that the body_class blocks resemble the rest of teh blocks in the specific templates

2019-12-12 07:10 UTC, keulinho commented on src/Storefront/Resources/views/storefront/page/content/single-cms-page.html.twig
> +    <body class="{% block base_body_classes %}is-ctl-{{ controllerName|lower }} is-act-{{ controllerAction|lower }}{% endblock %}">
please rename the block to `single_cms_page_body_classes`

2019-12-12 07:10 UTC, keulinho commented on src/Storefront/Resources/views/storefront/page/error/error-maintenance.html.twig
> +    <body class="{% block base_body_classes %}is-ctl-{{ controllerName|lower }} is-act-{{ controllerAction|lower }}{% endblock %}">
please rename this block to `error_maintenance_body_classes`

2019-12-12 07:42 UTC, stefanpoensgen commented
should be fine now. sorry, i could have noticed that. just stupid copy/paste :)

2019-12-12 09:44 UTC, keulinho approved these changes

2019-12-17 09:01 UTC, keulinho commented
Thanks again for your contribution @stefanpoensgen :blue_heart: :tada: 

We've merged your changes in our bugfix integration branch that will be integrated in the 6.1 release branch shortly.

2019-12-17 09:01 UTC, closed without merging