Fix german translations - administration Part 2
shopware/shopware pull request #531
Opened 2020-02-13 18:15 UTC by tinect

### 1. Why is this change necessary?
Currently, there are some errors in German translations and languagefiles.
Additionally to #480 

### 2. What does this change do, exactly?
Fixes German translations more admin-modules.
- misleading context to English source, including punctuation mark
- grammar
- spelling
- add missing translations
- fix translation in German translation for taxes

Sorry, currently I haven't that much time to check all modules in detail. But this will follow. Promised.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

2020-03-05 16:35 UTC, GitEvil requested changes

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json
> +      "labelErrorStateChange": "Beim setzen des Status ist ein Fehler aufgetreten. Zusätzliche Informationen:",
```suggestion
      "labelErrorStateChange": "Beim Setzen des Status ist ein Fehler aufgetreten. Zusätzliche Informationen:",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-product/snippet/de-DE.json
> +      "placeholderRule": "Bitte wählen",
Placeholder bitte immer mit den "..."

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-product/snippet/de-DE.json
> +      "emptyStateDescription": "Für dieses Produkt existiert noch keine Cross Selling Konfiguration.",
```suggestion
      "emptyStateDescription": "Für dieses Produkt existiert noch keine Cross Selling-Konfiguration.",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-profile/snippet/de-DE.json
> +      "placeholderNewPassword": "Gib Dein neues Passwort ein ...",
```suggestion
      "placeholderNewPassword": "Gib ein neues Passwort ein ...",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-promotion/snippet/de-DE.json
> +                "errorNoPatternMessage": "Bitte gib ein Muster für Deine Codes an!",
```suggestion
                "errorNoPatternMessage": "Bitte gib ein Muster für Deine Codes an.",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-promotion/snippet/de-DE.json
> +                "successGeneratedMessage": "{count} neue Codes wurden generiert!",
```suggestion
                "successGeneratedMessage": "{count} neue Codes wurden generiert.",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-country/snippet/de-DE.json
> +      "placeholderName": "Namen eingeben",
```suggestion
      "placeholderName": "Namen eingeben ...",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-country/snippet/de-DE.json
> +      "placeholderIso": "ISO-Code eingeben",
```suggestion
      "placeholderIso": "ISO-Code eingeben ...",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/snippet/de-DE.json
> +      "tooltipTechnicalName": "Der technische Name muss eindeutig sein und kann nicht mehr verändert werden."
```suggestion
      "tooltipTechnicalName": "Der technische Name muss eindeutig sein und kann später nicht mehr verändert werden."
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json
> +      "helpTextItemsPerPage": "Anzahl an Positionen pro Seite ...",
```suggestion
      "helpTextItemsPerPage": "Anzahl der Positionen pro Seite.",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-language/snippet/de-DE.json
> +      "placeholderName": "Namen eingeben",
```suggestion
      "placeholderName": "Namen eingeben ...",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-language/snippet/de-DE.json
> +      "placeholderPleaseSelect": "Bitte wählen",
```suggestion
      "placeholderPleaseSelect": "Bitte wählen ...",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-mailer/snippet/de-DE.json
> +      "helpText": "Für mehr Information, besuche die <a href='https://docs.shopware.com/de/shopware-6-de'>Dokumentation</a>"
```suggestion
      "helpText": "Für mehr Informationen, besuche die <a href='https://docs.shopware.com/de/shopware-6-de'>Dokumentation</a>"
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-number-range/snippet/de-DE.json
> +      "placeholderStart": "Startnummer eingeben",
```suggestion
      "placeholderStart": "Startnummer eingeben ...",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-payment/snippet/de-DE.json
> +      "placeholderDescription": "Beschreibung eingeben",
```suggestion
      "placeholderName": "Namen eingeben ...",
      "placeholderPosition": "Position eingeben ...",
      "placeholderDescription": "Beschreibung eingeben ...",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-shopware-updates/snippet/de-DE.json
> +        "validShopwareLicense": "Deine aktuelles Shopware ist veraltet. Möglicherweise möchtest Du ein Update in Betracht ziehen.",
```suggestion
        "validShopwareLicense": "Deine Shopware-Version ist veraltet. Du solltest ein Update in Betracht ziehen.",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-shopware-updates/snippet/en-GB.json
> +      "info": "What's New?",
```suggestion
      "info": "What's new?",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-tax/snippet/de-DE.json
> +      "placeholderSearchBar": "Durchsuche Steuern"
```suggestion
      "placeholderSearchBar": "Durchsuche Steuern ..."
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-tax/snippet/de-DE.json
> +      "emptyStateDescription": "Füge weitere Steuerraten für verschiedene Länder hinzu.",
```suggestion
      "emptyStateDescription": "Füge weitere Steuersätze für verschiedene Länder hinzu.",
```

2020-03-05 16:35 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-tax/snippet/en-GB.json
> +      "searchBarPlaceholder": "Search Countries...",
```suggestion
      "searchBarPlaceholder": "Search countries...",
```

2020-03-05 16:51 UTC, tinect commented on src/Administration/Resources/app/administration/src/module/sw-product/snippet/de-DE.json
> +      "placeholderRule": "Bitte wählen",
Alles klar. Ich passe english dann auch entsprechend an, okay?

2020-03-06 07:48 UTC, marcelbrode commented on src/Administration/Resources/app/administration/src/module/sw-product/snippet/de-DE.json
> +      "placeholderRule": "Bitte wählen",
Um eventuelle Arbeit direkt präventiv zu vermeiden: Im Deutschen mit Leerzeichen zwischen Wort und Ellipsis und im englischen nicht!

Im Englischen pflegen wir das aber auch so, ja :)

2020-03-09 09:47 UTC, tinect commented
@GitEvil Ready :-)

2020-03-10 09:56 UTC, GitEvil commented on src/Administration/Resources/app/administration/src/module/sw-settings-tax/snippet/en-GB.json
> +      "placeholderStates": "Add States..."
```suggestion
      "placeholderStates": "Add states..."
```

2020-03-10 09:57 UTC, GitEvil approved these changes

2020-03-10 12:51 UTC, pantrtxp commented
Hi @tinect, you still need to accept the "Contributor License Agreement" before we can go on with this PR

2020-03-21 22:59 UTC, tinect commented
@pantrtxp Now it's rebased to master.

2020-03-23 09:58 UTC, GitEvil approved these changes

2020-03-23 13:33 UTC, GitEvil approved these changes

2020-03-23 13:57 UTC, closed without merging

2020-03-23 13:57 UTC, pantrtxp commented
Thank you for your contribution :blue_heart: :tada: