Extract hardcoded options in cms administration
shopware/shopware pull request #571
Opened 2020-02-22 02:57 UTC by JoshuaBehrens

### 1. Why is this change necessary?
Add services and blocks to manipulate selection fields more easily and centralized. E.g. when you add a new product box layout you have to change override three twig blocks to add an option. Two of these blocks surround the selections and not the options. So only one can override the selection successfully in a not update-safe way. If I add a new cms block that shall also support product box layouts I can add the standard entries but I won't be automatically be aware of new entries.

### 2. What does this change do, exactly?
Move every non-null hardcoded option in a selection into a cms service to provide these and possibly future values.

### 3. Describe each step to reproduce the issue or behaviour.
1. Add product box layout
2. Override multiple twig js blocks (non update-safe and competitive to other bundles)
3. Add new cms block with product box layout selection but without new product box layout from other plugin 🙄
4. 💢 

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-02-26 10:28 UTC, jleifeld commented
Hey Joshua,

we think your PR is awesome! 👍 It allows easier modifications for plugin developers.

I have some ideas to make it even more awesome, because I saw some pitfalls in your implementation:
- Performance: The functions get called everytime Vue rerender the view
- Runtime Updates: A plugin developer can not add an option on the fly. The view don´t react automatically to this change

To solve these problems I would put all your state information in the store (`cms-page.state.js`):

Example:
```
...
state: {
        currentPage: null,
        currentMappingEntity: null,
        currentMappingTypes: {},
        currentDemoEntity: null,
        pageEntityName: 'cms_page',
        defaultMediaFolderId: null,
        currentCmsDeviceView: 'desktop',
        selectedSection: null,
        selectedBlock: null,
        isSystemDefaultLanguage: true,
        fieldOptions: { // you can choose a better name if you want ;)
            pageTypes: {
                page: {
                    label: 'sw-cms.detail.label.pageTypeShopPage'
                },
                landingpage: {
                    label: 'sw-cms.detail.label.pageTypeLandingpage'
                },
                product_list: {
                    label: 'sw-cms.detail.label.pageTypeCategory'
                    /*
                        will be implemented in the future
                    },
                    product_detail: {
                        label: 'sw-cms.detail.label.pageTypeProduct'
                    */
                }
            },
            alignments: {
                'flex-start': {
                    label: 'sw-cms.elements.general.config.label.verticalAlignTop',
                    vertical: true
                },
                center: {
                    label: 'sw-cms.elements.general.config.label.verticalAlignCenter',
                    vertical: true
                },
                'flex-end': {
                    label: 'sw-cms.elements.general.config.label.verticalAlignBottom',
                    vertical: true
                }
            },
            ...
        }
    },
...
```
Then you need mutation functions for setting new values. 



Values which returns modified data like 
```
getVerticalAlignments() {
        return Object.fromEntries(
            Object.entries(this.getAlignments())
                .filter(config => config[1] && config[1].vertical)
        );
    }
```
can be moved in Getters. Then Vue can automatically cache these and only recalculate when some dependency gets updated.

This allows Vue to dynamically react to changes and don´t call the functions for every rerender of the view. These gives the administration a better performance and plugin developer can add options on the fly and everything updates automatically :)



What would do you think? Would you agree with the idea? If yes, it would be awesome to refactor your PR to the strategy :)

2020-02-26 11:16 UTC, JoshuaBehrens commented
I really like your thoughts about the performance. I am familiar with vuex so this is not an issue for me.

`fieldOptions` suits.

So there would be a method that is used like this
```
commit('upsertAlignment', {key: 'foobar', label: 'foobar', vertical: true})
```
?
In my idea you add alignments like you add languages to the snippet management. Just a onliner 
```
Shopware.Server().get('...').upsertAlignment('foobar', {label: 'foobar', vertical: true})
```
that can be easily added. Can I alter the states already at plugin injection as well?

2020-02-26 12:16 UTC, jleifeld commented
The vuex store is directly available when the plugin get injected. Therefore, you can add language at every time in your plugin with this command:
```js
Shopware.State.commit('cmsPageState/yourMutationFunctionName', yourPayload);
```

2020-02-26 12:47 UTC, JoshuaBehrens commented
I like the benefits you stated. Let's see when I have time to amend this 😄 you might've seen my commit schedules

2020-02-27 07:42 UTC, jleifeld commented
I know, i know 😄 

You are one of the best contributors here on Github 😉 Take your time and don´t hurry.

I will set the label to `Incomplete` and when you are ready I will remove the label 👍

2020-03-31 12:18 UTC, pantrtxp commented
Hi @JoshuaBehrens,

is there any chance you'll get to this PR any time soon?
This is pending over a month. If you still need time I'd like to close this PR due to inactivity and you are free to create a new one once this is ready :slightly_smiling_face: 

Sunny regards
Pantrtxp

2020-03-31 13:37 UTC, JoshuaBehrens commented
I already rebased it yesterday evening #nojoke. I am working on it. I just push my rebase. I think about putting helpers into cms-state mixin. That is my state of work :D

2020-04-03 00:54 UTC, JoshuaBehrens commented
I need a short review. I fiddle around with your requested feature to change data live. But it seems not to change live.

I pushed one example to try it. It is the selection for block categories.
`Shopware.State.commit('cmsPageState/setFieldOptionBlockCategory', {name:'foobar', label: 'party'})` does add the new category to the state. You can test it by reading the state `Shopware.State.get('cmsPageState').fieldOptions.blockCategory.foobar`. The UI is not updating though. When I change the page and come back to the cmsPage editor and open up the block add sidebar there is my newly added block category.

Wrapping the read property in the template into a computed property does not change anything. How do I make it as reactive as intended?

2020-04-05 21:10 UTC, JoshuaBehrens commented
I just had to use `Vue.set` in the state to make it reactive 🎉  Have a look at the refactory. That should match your proposal.

2020-04-08 09:28 UTC, JoshuaBehrens commented
As @mitelg once suggested I should be part of the authors list, well I added myself now :)

2020-04-09 08:10 UTC, JoshuaBehrens commented
Avatar is fixed

2020-06-20 14:48 UTC, JoshuaBehrens commented
Rebase is out

2020-11-24 14:42 UTC, philipgatzka requested changes
Sorry it took so long :see_no_evil: Nice idea :ok_hand: I'd just like to ask you to write simple tests for the mutators. You could try to extract the validation/preparation into an action and keep the mutations simple, this would also decrease the duplication a little and presumably make it less repetitive to test this.

2020-11-24 15:46 UTC, JoshuaBehrens commented
I'll have a look how to test this. Any reference tests you suggest for Vuex tests?

2020-11-25 08:24 UTC, philipgatzka commented
Thanks :+1: There's one test already using the `cms-page` store, `platform/src/Administration/Resources/app/administration/test/module/sw-product/view/sw-product-detail-base.spec.js`. I don't think you'll need to properly register the whole thing like it's done there though. For your mutations/actions, I think the [vuex testing guide](https://vuex.vuejs.org/guide/testing.html#testing) from vuejs.org is a good orientation. Here they import the store and test the methods in isolation.

2020-11-25 09:09 UTC, JoshuaBehrens commented
Thank you for the explanation. This will help me a lot here. Gonna polish the code 😁

2020-12-09 10:27 UTC, philipgatzka commented
Hello, we're closing this pull request due to inactivity. If this change is still important to you, feel free to create a new pull request.

For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline.

2020-12-09 10:27 UTC, closed without merging