Use min purchase as lower bound for listing price calculation
shopware/shopware pull request #782
Opened 2020-04-28 08:46 UTC by JoshuaBehrens

### 1. Why is this change necessary?
When a product only has prices from starting at quantity 150 the listing price is generated for the hidden default parameter of quantity 1. As there is no price for below 150 it fails to load the listing.

### 2. What does this change do, exactly?
Use the min purchase information to define the lower bound of the listing price.

### 3. Describe each step to reproduce the issue or behaviour.
1. Create prices that do not start below 2
2. Load a listing

### 4. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-04-28 08:47 UTC, JoshuaBehrens commented
This is a breaking change. Other options to fulfil the use case are welcome.

2020-06-15 00:35 UTC, JoshuaBehrens commented
Rebase is out

2020-11-12 12:40 UTC, philipgatzka requested changes
Hi @JoshuaBehrens , thank you for keeping this up-to-date :wink: Please target the major branch, since this is a breaking change and add tests aswell as a changelog entry for your change.

2020-11-15 18:42 UTC, JoshuaBehrens commented
@philipgatzka I added a test. Just to be sure: on major there are no changelogs yet, are there?

2020-11-15 18:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/platform?pullRequest=782) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=782) before we can accept your contribution.<br/>**3** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: jleifeld<br/>:white_check_mark: jkrzefski<br/>:white_check_mark: JoshuaBehrens<br/>:x: hungmac-sw<br/>:x: leichteckig<br/>:x: pweyck<br/>:x: mitelg<br/>:x: ssltg<br/>:x: OliverSkroblin<br/>:x: taltholtmann<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/platform?pullRequest=782) it.</sub>

2020-11-26 08:38 UTC, philipgatzka commented
Hi @JoshuaBehrens , there are, but I just realised that this will probably need a warning in the master branch changelog as well. It would be unnecessarily complicated to do that via github pull requests though, so I'll just take care of that :wink:

2020-11-26 09:21 UTC, philipgatzka requested changes
Since the tests didn't run correctly in the github pipeline, I quickly had a look at this locally - your testcase seems fine but I think the change in the subscriber is not working as intended. This is what I get back in `$prices['from']`:
```
from = {Shopware\Core\Checkout\Cart\Price\Struct\QuantityPriceDefinition} [7]
 price = {float} 100.0
 taxRules = {Shopware\Core\Checkout\Cart\Tax\Struct\TaxRuleCollection} [2]
 quantity = {int} 1
 isCalculated = true
 referencePriceDefinition = null
 listPrice = null
 extensions = {array} [0]
```
And the product is okay AFAICT:
```
$product = {Shopware\Core\Content\Product\SalesChannel\SalesChannelProductEntity} [106]
 minPurchase = {int} 5
```
Please verify this once more :slightly_smiling_face:

2020-12-10 10:33 UTC, J-Rahe commented
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request.
For more information about our contribution guidelines, see https://docs.shopware.com/en/shopware-platform-dev-en/contribution/contribution-guideline

2020-12-10 10:33 UTC, closed without merging