Add twig blocks to the `sw-product-detail` template for the sidebar and sidebar-items
shopware/shopware pull request #876
Opened 2020-05-12 12:07 UTC by hanneswernery

### 1. Why is this change necessary?

As discussed with @mitelg, in the product detail page, the sidebar and its sidebar items are not wrapped in a twig block. Hence the current sidebar item (media sidebar) is shown in all tabs of the detail page. This prevents plugins from modifying or extending the sidebar with additional sidebar-items.

### 2. What does this change do, exactly?

This PR adds twig blocks to the sidebar and sidebar-items.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-05-18 08:59 UTC, tobiasberge commented
Hi @hanneswernery,

thank you for your contribution. 👍 

Could you add the block names to the Changelog entry like this and fix the merge conflicts?

* Added twig blocks to the `sw-product-detail` template for the sidebar and sidebar-items
  * `sw_product_detail_sidebar`
  * `sw_product_detail_sidebar_additional_items`

Since this is not a breaking change you can also use the `6.2` branch as your target branch. Then your changes will be in the next patch release. The `master` branch will become the next minor release at some point.

Best regards
Tobias

2020-05-18 09:00 UTC, tobiasberge requested changes

2020-05-18 09:00 UTC, tobiasberge commented on CHANGELOG-6.2.md
> +    * Added twig blocks to the `sw-product-detail` template for the sidebar and sidebar-items
```suggestion
    * Added twig blocks to the `sw-product-detail` template for the sidebar and sidebar-items
      * `sw_product_detail_sidebar`
      * `sw_product_detail_sidebar_additional_items`
```

2020-05-18 09:49 UTC, hanneswernery commented
Hi @tobiasberge! All done.

2020-05-25 13:20 UTC, tobiasberge approved these changes

2020-05-25 14:20 UTC, closed without merging

2020-05-25 14:22 UTC, tobiasberge commented
Hi @hanneswernery,

thank you for fixing the suggestions. You PR was merged to `6.2`. 🎉 

Best regards
Tobias