[NEXT-6109]
shopware/shopware pull request #899
Opened 2020-05-14 10:33 UTC by jinnoflife

### 1. Why is this change necessary?
To provide and display the `supportText` inside the theme

### 2. What does this change do, exactly?
Add possibility to fill and display the `supportText`

### 3. Describe each step to reproduce the issue or behaviour.
Try to add supportText

### 4. Please link to the relevant issues (if any).
#812
Video: https://vimeo.com/418392136/0bd1eb2d46

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
  - Is this needed? There aren't any
- [x] I have squashed any insignificant commits
- [x] I have written or adjusted the documentation according to my changes
  - Due to the missing helpText-Field in the documentation I didn't adjust those
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-05-14 10:34 UTC, jinnoflife commented
I'll fix the tests right now

2020-05-14 11:17 UTC, mitelg commented on src/Storefront/Migration/Migration1589443055AddThemeSupportText.php
> +        $connection->executeUpdate('ALTER TABLE `theme_translation` ADD `support_texts` json NULL AFTER `labels`;');
why should a textfield be of type json?

2020-05-14 11:19 UTC, mitelg commented on src/Storefront/Migration/Migration1589443055AddThemeSupportText.php
> +        $connection->executeUpdate('ALTER TABLE `theme_translation` ADD `support_texts` json NULL AFTER `labels`;');
never mind. same logic as the other texts

2020-05-14 13:36 UTC, leichteckig commented
QA approved, as soon as you remove the duplicates for testing purposes :+1:

2020-05-14 13:49 UTC, pantrtxp commented
@jinnoflife can you please resolve your conflicts :)?

2020-05-14 14:03 UTC, jinnoflife commented
@pantrtxp done
@leichteckig which duplicates do you mean?

2020-05-14 14:08 UTC, mitelg commented
@jinnoflife please add the `fixes #123` hint to your commit message

2020-05-14 15:25 UTC, tobiasberge requested changes

2020-05-14 15:25 UTC, tobiasberge commented on src/Administration/Resources/app/administration/test/app/component/form/__snapshots__/sw-radio-field.spec.js.snap
> +  <!---->
Is this wanted? 🤔

2020-05-14 15:26 UTC, tobiasberge approved these changes

2020-05-14 15:31 UTC, mitelg commented
@jinnoflife please reabase your branch :blush: there are merge conflicts

2020-07-17 09:30 UTC, pweyck commented
Hi @jinnoflife, could you please rebase this onto master and resolve @tobiasberge's comment?

2020-07-17 11:18 UTC, tobiasberge commented
@pweyck Sorry my bad this was auto generated by jest snapshot. It just looked weird.

2020-07-30 11:28 UTC, closed without merging